---
title: "Retirement Locator"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    #vertical_layout: fill
    theme:
      version: 4
      bootswatch: lux
      base_font: 
        google: Castoro
      heading_font:
        google: Lato
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: Roboto Mono
          local: false
      font_scale: .875
    logo: ./www/img/site-logo.png
    # includes: 
    #   after_body: ./includes/footer.html
    # css: www/custom-styles.css
runtime: shiny
---


```{r load-data}
data("retirementLoc", package = "retirementLoc")
```

```{r load-libraries}
library(shinyWidgets)
library(shiny)
library(leaflet)
library(htmltools)
library(plotly)
```

## Criteria {.sidebar data-width=350}

```{r shiny-inputs}
# Input: State ----
pickerInput("stname", "State:",
                choices = sort(unique(retirementLoc$stname)),
                selected = c("Alabama", "Florida", "Georgia",
                             "Mississippi", "North Carolina",
                             "South Carolina"),
                multiple = T,
                options = list(
                `actions-box` = TRUE,
                `deselect-all-text` = "None",
                `select-all-text` = "All",
                `none-selected-text` = "zero"
                )
)
# Input: population ----
numericRangeInput(
  inputId = "pop_2020", label = "2020 Population",
  value = c(min(retirementLoc$pop_2020),
            max(retirementLoc$pop_2020))
)
# Input: Population Change  ----
sliderInput("pct_pop_change", "% Pop. Change 2010 to 2020:",
         min = min(retirementLoc$pct_pop_change, na.rm = T),
         max = max(retirementLoc$pct_pop_change, na.rm = T),
         value = c(min(retirementLoc$pct_pop_change, na.rm = T),
                   max(retirementLoc$pct_pop_change, na.rm = T)),
         step = 1,
         round = TRUE
)
# Input: Partisan Lean  ----
sliderInput("partisan_lean", "% Partisan Lean 2020:",
         min = min(retirementLoc$partisan_lean, na.rm = T),
         max = max(retirementLoc$partisan_lean, na.rm = T),
         value = c(min(retirementLoc$partisan_lean, na.rm = T),
                   max(retirementLoc$partisan_lean, na.rm = T)),
         step = 1,
         round = 1
)
# Input: Life Expectancy  ----
sliderInput("life_exp", "Life Expectancy (years):",
         min = min(retirementLoc$life_exp, na.rm = T),
         max = max(retirementLoc$life_exp, na.rm = T),
         value = c(min(retirementLoc$life_exp, na.rm = T),
                   max(retirementLoc$life_exp, na.rm = T)),
         step = 1,
         round = 1
)

# Input: Average annual temperature  ----
sliderInput("avg_ann_temp", "Avg. Annual Temp:",
         min = min(retirementLoc$avg_ann_temp, na.rm = T),
         max = max(retirementLoc$avg_ann_temp, na.rm = T),
         value = c(min(retirementLoc$avg_ann_temp, na.rm = T),
                   max(retirementLoc$avg_ann_temp, na.rm = T))
)
# Input: Average annual temperature  ----
sliderInput("broadband_2017", "% Broadband 2017:",
         min = min(retirementLoc$broadband_2017, na.rm = T),
         max = max(retirementLoc$broadband_2017, na.rm = T),
         value = c(min(retirementLoc$broadband_2017, na.rm = T),
                   max(retirementLoc$broadband_2017, na.rm = T))
)

# Input: Average annual temperature  ----
sliderInput("years_to_payoff", "Home payoff in years:",
         min = min(retirementLoc$years_to_payoff, na.rm = T),
         max = max(retirementLoc$years_to_payoff, na.rm = T),
         value = c(min(retirementLoc$years_to_payoff, na.rm = T),
                   max(retirementLoc$years_to_payoff, na.rm = T))
)
```


```{r filtered-dataset, include=F}
filtered <- reactive({
    retirementLoc %>% 
      dplyr::filter(stname %in% input$stname) %>%
      dplyr::filter(pop_2020 >=input$pop_2020[1] & pop_2020 <= input$pop_2020[2]) %>%
      dplyr::filter(pct_pop_change >=input$pct_pop_change[1] & pct_pop_change <= input$pct_pop_change[2]) %>% 
      dplyr::filter(partisan_lean >=input$partisan_lean[1] & partisan_lean <= input$partisan_lean[2]) %>% 
      dplyr::filter(life_exp >= input$life_exp[1] & life_exp <= input$life_exp[2]) %>% 
      dplyr::filter(avg_ann_temp >= input$avg_ann_temp[1] & avg_ann_temp <= input$avg_ann_temp[2]) %>% 
      dplyr::filter(broadband_2017 >= input$broadband_2017[1] & broadband_2017 <= input$broadband_2017[2]) %>% 
      dplyr::filter(years_to_payoff >= input$years_to_payoff[1] & years_to_payoff <= input$years_to_payoff[2])
        # filter(type %in% input$type | !complete.cases(type)) %>%
        # filter(class %in% input$class | class == "")S
  })
```
 
## Main {.tabset}

### Map

```{r render-map}
renderLeaflet({
  df <- filtered()
  leaflet(df) %>% 
  addTiles() %>% 
  setView(-85.65, 32.0285, zoom = 6) %>% 
  addMarkers(lng = ~lon,
             lat = ~lat,
             popup = paste0("County: ", df$ctyname, "<br>",
                            "Pop 2020: ", df$pop_2020, "<br>",
                            "Growth: ", df$pct_pop_change,"%", "<br>",
                            "Part Lean: ", df$partisan_lean, "%", "<br>",
                            "Life exp: ", df$life_exp, "<br>",
                            "Avg temp: ", df$avg_ann_temp, "<br>",
                            "Broadband: ", df$broadband_2017,"%", "<br>",
                            "Payoff: ", df$years_to_payoff, " years", "<br>")
             )
})
```

### Table

```{r render-table}
DT::renderDataTable({
 df <- filtered()
 df[, 4:12]
})
```

### Plot

```{r render-plotly}
renderPlotly({
  df <- filtered()
  fig <- plot_ly(type = 'scatter', mode = 'markers') 
  fig <- fig %>% 
    add_trace(
      x = df$pct_pop_change,
      y = df$years_to_payoff,
      text = df$ctyname,
      hoverinfo = 'text',
      showlegend = TRUE,
      color = df$stname,
      size = df$pop_2020
    )
  fig <- fig %>%
  layout(
    title = list(text="House Affordability and Population Growth",
      size = 10),
    xaxis = list(title = "Pop. Change (%)"),
    yaxis = list(title = "Years to Payoff",
                 showline= T)
    )

fig
})
```

